### PR TITLE
Add test

### PR DESCRIPTION
**Pull request by vecpeng**
The test cover is only 15.5%.There is a long way to improve it.
image

### CODE REVIEW

**Comment by dgrr** [comment]
Hello. This pull request includes the contents of the other, as far as I see. I'll take a look later on the RFC about the HPACK table, because I am not sure if we need an uint32.

**Comment by vecpeng** [comment]
I see that the implementation of Go also use uint32 instead of int.
https://github.com/bradfitz/http2/blob/master/hpack/hpack.go#L45

**Comment by dgrr** [comment]
> @dgrr , thanks for your review. I find that the implementation of Go also use uint32 instead of int. https://github.com/bradfitz/http2/blob/master/hpack/hpack.go#L45.

It's fine. I guess it's because the table size can only be a positive number.

**Comment by vecpeng** [comment]
@dgrr, Sorry, it seems that workflow fails because some lint problems.And now it is fixed.

**Comment by dgrr** [comment]
Thanks for your pull request!

**Pull request merged**
